# Generated by Django 5.1.15 on 2026-04-28 22:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('projects', '0001_initial'),
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('purchase', 'Compra'), ('sale', 'Venta'), ('return_in', 'Devolución a stock'), ('return_out', 'Devolución a proveedor'), ('adjustment', 'Ajuste'), ('initial', 'Inicial')], max_length=24)),
                ('quantity', models.IntegerField(help_text='Positivo entra, negativo sale.')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('ARS', 'ARS')], default='USD', max_length=3)),
                ('rate_used', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='products.product')),
                ('project_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='projects.projectitem')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='purchases.purchase')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['product', 'kind'], name='stock_stock_product_5b5641_idx')],
            },
        ),
    ]
