# Generated by Django 5.1.15 on 2026-04-28 22:09

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('tax_id', models.CharField(blank=True, default='', max_length=64)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('quoted', 'Cotizado'), ('approved', 'Aprobado'), ('in_progress', 'En curso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='quoted', max_length=24)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('ARS', 'ARS')], default='USD', max_length=3)),
                ('rate_used', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('extra_charges', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cost_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cost_total_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('profit_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('margin_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('stock_committed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('line_cost_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_items', to='products.product')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.project')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
