# Generated by Django 5.1.15 on 2026-04-29 19:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectitem',
            name='iva_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
    ]
