# Generated by Django 5.1.15 on 2026-04-29 19:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='iva_pct',
            field=models.DecimalField(choices=[(Decimal('21.00'), '21%'), (Decimal('10.50'), '10.5%')], decimal_places=2, default=Decimal('21.00'), max_digits=5),
        ),
    ]
