# Generated by Django 5.1.15 on 2026-04-28 22:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=14)),
                ('source', models.CharField(choices=[('dolarapi', 'DolarAPI'), ('manual', 'Manual')], default='dolarapi', max_length=32)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('fetched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-fetched_at',),
            },
        ),
    ]
